name: ml_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip:
    - -e .
    - ipykernel
